name = "mizhi-card-api"
main = "src/index.ts"
compatibility_date = "2025-05-16"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mizhi-card-db"
database_id = "dc3a7fc5-3b90-4c6a-805d-a0ae8ec1c98b"

[[kv_namespaces]]
binding = "CARD_IMAGES"
id = "476ae98caf03486fa32786fcbc59cc75"

[env.production.vars]
ALLOWED_ORIGIN = "https://mizhi-card.pages.dev"

[[env.production.routes]]
pattern = "api.mizhi-card.pages.dev/*"
